# ref. https://goreleaser.com/customization/build/
version: 2

builds:
  - id: devkit-cli
    main: ./cmd/devkit/main.go
    binary: devkit
    flags:
      - -v
    ldflags:
      - -X 'devkit-cli/pkg/telemetry.embeddedTelemetryApiKey={{ .Env.TELEMETRY_TOKEN }}'
      - -X 'devkit-cli/pkg/context.embeddedDevkitReleaseVersion={{.Version}}'
    # windows is ignored by default, as the `goos` field by default only
    # contains linux and darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: layr-labs
    name: devkit-cli

  draft: true