version: 0.0.3
config:
  project:
    name: "my-avs"
    version: "0.1.0"
    context: "devnet"
    project_uuid: ""
    templateBaseUrl: "https://github.com/Layr-Labs/hourglass-avs-template"
    templateVersion: "v0.0.14"
    templateLanguage: "go"
    telemetry_enabled: false
